#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Projeto_S2B_Main.Resource", IsApplication=true)]

namespace Projeto_S2B_Main
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int creditCard = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int debitCard = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int delete = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int money = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int monoandroidsplash = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int poupanca = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060006
			public const int ScrollViewID = 2131099654;
			
			// aapt resource value: 0x7f060023
			public const int adicionarAtributo = 2131099683;
			
			// aapt resource value: 0x7f060026
			public const int adicionarAttr = 2131099686;
			
			// aapt resource value: 0x7f06001f
			public const int atributoNome = 2131099679;
			
			// aapt resource value: 0x7f060021
			public const int atributoTipo = 2131099681;
			
			// aapt resource value: 0x7f060027
			public const int atributosView = 2131099687;
			
			// aapt resource value: 0x7f060024
			public const int autoCompleteGrupo = 2131099684;
			
			// aapt resource value: 0x7f06003b
			public const int button1 = 2131099707;
			
			// aapt resource value: 0x7f060025
			public const int categoriaNome = 2131099685;
			
			// aapt resource value: 0x7f060017
			public const int categorias = 2131099671;
			
			// aapt resource value: 0x7f06001b
			public const int categoriasView = 2131099675;
			
			// aapt resource value: 0x7f060034
			public const int contaButton = 2131099700;
			
			// aapt resource value: 0x7f060016
			public const int contas = 2131099670;
			
			// aapt resource value: 0x7f06001d
			public const int contasView = 2131099677;
			
			// aapt resource value: 0x7f060029
			public const int criarAtributo = 2131099689;
			
			// aapt resource value: 0x7f06001c
			public const int criarCategoria = 2131099676;
			
			// aapt resource value: 0x7f06001e
			public const int criarConta = 2131099678;
			
			// aapt resource value: 0x7f060042
			public const int criarLancamento = 2131099714;
			
			// aapt resource value: 0x7f060044
			public const int criarTransferencia = 2131099716;
			
			// aapt resource value: 0x7f06002b
			public const int editText1 = 2131099691;
			
			// aapt resource value: 0x7f060032
			public const int editText2 = 2131099698;
			
			// aapt resource value: 0x7f06003a
			public const int editText3 = 2131099706;
			
			// aapt resource value: 0x7f060040
			public const int editText4 = 2131099712;
			
			// aapt resource value: 0x7f060022
			public const int excluirAtributo = 2131099682;
			
			// aapt resource value: 0x7f060028
			public const int excluirCategoria = 2131099688;
			
			// aapt resource value: 0x7f060033
			public const int excluirConta = 2131099699;
			
			// aapt resource value: 0x7f060018
			public const int lancamentos = 2131099672;
			
			// aapt resource value: 0x7f060041
			public const int lancamentosView = 2131099713;
			
			// aapt resource value: 0x7f060008
			public const int linearLayout1 = 2131099656;
			
			// aapt resource value: 0x7f060010
			public const int linearLayout2 = 2131099664;
			
			// aapt resource value: 0x7f060002
			public const int moneyLabel = 2131099650;
			
			// aapt resource value: 0x7f06002a
			public const int novaCategoria = 2131099690;
			
			// aapt resource value: 0x7f06002d
			public const int radioButton1 = 2131099693;
			
			// aapt resource value: 0x7f06002e
			public const int radioButton2 = 2131099694;
			
			// aapt resource value: 0x7f06002f
			public const int radioButton3 = 2131099695;
			
			// aapt resource value: 0x7f060030
			public const int radioButton4 = 2131099696;
			
			// aapt resource value: 0x7f06002c
			public const int radioGroup1 = 2131099692;
			
			// aapt resource value: 0x7f06001a
			public const int sair = 2131099674;
			
			// aapt resource value: 0x7f060031
			public const int saldoLabel = 2131099697;
			
			// aapt resource value: 0x7f060007
			public const int scrollView1 = 2131099655;
			
			// aapt resource value: 0x7f060035
			public const int spinner1 = 2131099701;
			
			// aapt resource value: 0x7f060036
			public const int spinner2 = 2131099702;
			
			// aapt resource value: 0x7f06003c
			public const int spinner3 = 2131099708;
			
			// aapt resource value: 0x7f060003
			public const int textContaRelacionada = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int textData = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int textLabel = 2131099648;
			
			// aapt resource value: 0x7f060005
			public const int textValor = 2131099653;
			
			// aapt resource value: 0x7f060009
			public const int textView1 = 2131099657;
			
			// aapt resource value: 0x7f060020
			public const int textView2 = 2131099680;
			
			// aapt resource value: 0x7f060037
			public const int textView3 = 2131099703;
			
			// aapt resource value: 0x7f060038
			public const int textView4 = 2131099704;
			
			// aapt resource value: 0x7f060039
			public const int textView5 = 2131099705;
			
			// aapt resource value: 0x7f06003d
			public const int textView6 = 2131099709;
			
			// aapt resource value: 0x7f06003e
			public const int textView7 = 2131099710;
			
			// aapt resource value: 0x7f06003f
			public const int textView8 = 2131099711;
			
			// aapt resource value: 0x7f060043
			public const int tranferenciasView = 2131099715;
			
			// aapt resource value: 0x7f060019
			public const int transferencia = 2131099673;
			
			// aapt resource value: 0x7f06000c
			public const int txtCategoria = 2131099660;
			
			// aapt resource value: 0x7f060015
			public const int txtComentarioT = 2131099669;
			
			// aapt resource value: 0x7f06000a
			public const int txtConta = 2131099658;
			
			// aapt resource value: 0x7f060012
			public const int txtContaD = 2131099666;
			
			// aapt resource value: 0x7f060011
			public const int txtContaO = 2131099665;
			
			// aapt resource value: 0x7f06000f
			public const int txtData = 2131099663;
			
			// aapt resource value: 0x7f060014
			public const int txtDataT = 2131099668;
			
			// aapt resource value: 0x7f06000b
			public const int txtFornecedor = 2131099659;
			
			// aapt resource value: 0x7f06000e
			public const int txtTipo = 2131099662;
			
			// aapt resource value: 0x7f06000d
			public const int txtValor = 2131099661;
			
			// aapt resource value: 0x7f060013
			public const int txtValorT = 2131099667;
			
			// aapt resource value: 0x7f060001
			public const int typeAccLabel = 2131099649;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int celula = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int celulaConta = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int celulalancamentos = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int detalhesDeLancamentos = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int detalhesDeTransferencia = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int telacategorias = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int telacontas = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int telacriaratributo = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int telacriarcategoria = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int telacriarconta = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int telafazertransferencia = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int telagerarlancamento = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int telalancamentos = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int telatransferencias = 2130903054;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Mono_Android_Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
